### PR TITLE
remove http:// in front of ${UPSTREAM}

### PR DESCRIPTION
**Pull request by fiorenzino**
Should be usefull the possbility to choise the protocoll:

-e UPSTREAM="backend:8080;172.17.0.5:60;container:5000"
-e UPSTREAM="http://backend:8080;http://172.17.0.5:60;https://container:5000"

I used a custom template to do that.

### CODE REVIEW

**Comment by jbtrystram** [comment]
I would keep this HTTP oriented, as it is simpler.
You can add a specific `vhost.conf` file for specifis needs.
This is already taken care of ( https://github.com/smashwilson/lets-nginx/blob/master/entrypoint.sh#L83 )

I recon that it is not documented in the README..

**Comment by jbtrystram** [comment]
Oh, and it is documented, I missed that !

> -v {PATH_TO_CONFIGS}:/configs:ro specify manual configurations for select domains. Must be in the form {DOMAIN}.conf to be recognized.

**Comment by fiorenzino** [comment]
wow, with your "secret conf" i resolved my question!
you can close my pull request!

thanks
fiorenzo

**Comment by jbtrystram** [comment]
:+1:

**Pull request closed without merging**
