### PR TITLE
Added support for WebSockets

### PR DESCRIPTION
**Pull request by syntropica**
This pull request adds support for WebSockets. I don't believe there's any drawback to including this in the default template (i.e., for non-WebSocket sites too).

### CODE REVIEW

**Comment by rgbkrk** [comment]
The main drawback here would be that nginx _will_ hold connections open for resources that are _not_ websockets, unless the upstream service closes them explicitly.

**Comment by smashwilson** [comment]
@rgbkrk Hmm. Am I reading [the nginx docs](http://nginx.org/en/docs/http/websocket.html) correctly in that something like this would only open a websocket connection if the client explicitly requested one?

```
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        ...

        location /chat/ {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
```

**Comment by smashwilson** [comment]
I'm mostly concerned about this being a potential DoS vector, though, and I suppose a malicious client could always include an `Upgrade` header either way...

**Comment by rgbkrk** [comment]
Well that's neat, didn't know about that nginx option. It's worth a shot. They still show it in the docs on a specific path though.

**Comment by syntropica** [comment]
Gargh, that's what I was going for, but I was a numpty and forgot to include the update to nginx.conf :-/

**Comment by smashwilson** [comment]
Ah, cool. Alright, sure, what's the worst that could happen :wink:

**Comment by rgbkrk** [comment]
👍

**Comment by syntropica** [comment]
Cheers folks :)

**Pull request merged**
