### PR TITLE
forgot to remove the domain-name in the certificate path.

### PR DESCRIPTION
**Pull request by jbtrystram**
see https://github.com/smashwilson/lets-nginx/pull/9

I forgot to remove the domain name in the certificate path.
Since a single cert is now generated, this would be an issue

Sorry about that

### CODE REVIEW

**Comment by smashwilson** [comment]
We don't control the directory structure of `/etc/letsencrypt/live`, though - that's managed by the letsencrypt client itself. Where does it put its certs when you have multiple SANs?

**Comment by jbtrystram** [comment]
Good question. I've run the test to find out ! The cert is stored in `/etc/letsencrypt/live/domain/` where domain is the **first** domain passed in the `--domain` arguments.
However : if one of the domains passed as arguments has already a LE certificate, then the new certificate is placed under that domain subfolder. Even if it's not the first `--domain` arguments.
In that case (when one ore more domains have already a certificate), the new certs is placed in the folder of the domain that first matches (i.e. the command is read from left to right, the first --domain that already exists is used to store the new cert)

EDIT : I also run another test with different domains (eg test.com & domain.org)
if you place everything into the same command, the behaviour is the same as above, even with different domains

Edit 2 : we might encounter [this issue](https://github.com/letsencrypt/letsencrypt/issues/2071) if a domain is removed from the proxy.

An easy solution, though, could be to stop checking if the certs already exits and always start from fresh (each time you start the container)

**Comment by smashwilson** [comment]
> An easy solution, though, could be to stop checking if the certs already exits and always start from fresh (each time you start the container)

No can do I'm afraid - that'll eat through your certificate quota. That's why the certificate cache exists in the first place :smile:

**Comment by smashwilson** [comment]
Oh! You mean stop checking and start fresh _when the SAN list has changed._ Yeah, that's totally reasonable behavior there. A little unfortunate but I don't think it can be avoided.

**Comment by greyslater** [comment]
Hello,

is there any progress going on?
I'd like to use your docker image again but unfortunately it was build with your upgraded code, so I can't use it even with only one domain.
Would be so great to get the function with multible SAN
Thanks

**Comment by jbtrystram** [comment]
yep i'm working on an easy fix, but i'm encountering an odd issue with let's encrypt.
I'll update this PR to let you know ;)

**Comment by jbtrystram** [comment]
Well, if anyone have an idea...
When running the script, in a freshly built container, I have this error : 

```
letsencrypt: error: unrecognized arguments:  -d s1.domain.net  -d s2.domain.net  --server https://acme-staging.api.letsencrypt.org/directory

```

When running this, on another machine with Letsencrypt installed (cloned official repo, ubuntu) :

```
letsencrypt certonly -d s1.domain.net -d s2.domain.net --standalone --server https://acme-staging.api.letsencrypt.org/directory --email email@domain.net --agree-tos --expand
```

It's running fine.
Any idea ?

**Comment by smashwilson** [comment]
This container uses the latest published version on pip, not a clone from master. Try using `--domain` instead of `-d`; maybe that's an alias they've added recently but not released.

**Comment by jbtrystram** [comment]
I tried this. The pip version does support the `-d` option.
If i hard-code the let's encrypt command in entrypoint.sh it's work. Using the generated one doesn't work, but i can't understand why.

Wow, i just found a solution, this is very strange : 

```
   echo "letsencrypt certonly "${letscmd}" \
    --standalone \
    "${SERVER}" \
    --email "${EMAIL}" --agree-tos \
    --expand " > /etc/nginx/lets
    /bin/bash /etc/nginx/lets
```

It works.
I don't understand why the straight solution does not.

**Comment by jbtrystram** [comment]
Okay : now it runs fine with that last commit.

This is an odd workaround though...

**Comment by smashwilson** [comment]
Yeah, passing bash arguments from a variable has some odd corner cases. I might take some time to find a better alternative at some point. In the meantime, this'll do.

**Comment by jbtrystram** [comment]
wow, quick merging ! 
I'm happy we got it working after all ! Sorry for the bumps during the process..

**Pull request merged**
